# Generated by Django 3.2.4 on 2021-06-24 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tweets', '0002_alter_tweet_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tweet',
            options={'ordering': ['-id']},
        ),
    ]
